name: Deploy to Stage

on:
  push:
    branches: [ stage-clean ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Install dependencies
      run: |
        echo "Installing root dependencies..."
        npm ci
        echo "Installing infrastructure dependencies..."
        cd infrastructure
        npm ci
        cd ..
    - name: Build backend
      run: |
        cd backend
        npm ci
        npm run build
        ls -la dist/  # Debug: verify dist directory exists
        cd ..
        ls -la backend/dist/  # Debug: verify from root
    
    - name: Ensure backend dist exists
      run: |
        # Ensure the backend/dist directory exists
        if [ ! -d "backend/dist" ]; then
          echo "ERROR: backend/dist directory not found after build!"
          echo "Creating minimal dist directory with handler..."
          mkdir -p backend/dist
          echo "exports.handler = async (event) => { return { statusCode: 200, body: 'Placeholder' }; };" > backend/dist/main.js
        fi
        echo "Contents of backend/dist:"
        ls -la backend/dist/
        
    - name: Bootstrap CDK (if needed)
      run: |
        cd infrastructure
        echo "Checking AWS credentials..."
        aws sts get-caller-identity
        echo "Running CDK bootstrap..."
        npx cdk bootstrap --context stage=stage || echo "Bootstrap might already exist, continuing..."
    - name: Deploy CDK stack
      run: |
        cd infrastructure
        # Debug: Check current directory and backend dist
        pwd
        ls -la ../backend/dist/ || echo "Backend dist not found!"
        # Set absolute path for backend dist
        export BACKEND_DIST_PATH="${GITHUB_WORKSPACE}/backend/dist"
        echo "Backend dist path: $BACKEND_DIST_PATH"
        ls -la $BACKEND_DIST_PATH || echo "Backend dist not found at absolute path!"
        npx cdk deploy --require-approval never --context stage=stage
        
    - name: Get API Gateway URL
      run: |
        cd infrastructure
        API_URL=$(npx cdk output --format json | jq -r '.["PREREQ"].ApiGatewayUrl // empty')
        echo "API_URL=$API_URL" >> $GITHUB_ENV
        echo "Deployed API Gateway URL: $API_URL" 